### PR TITLE
Podcast talk

### PR DESCRIPTION
**Pull request by buddhaplex**
Added a page covering my Lightning Talk on 8/20, with video and embeded slides.

### CODE REVIEW

**Comment by colinrubbert** [comment]
Looks good @buddhaplex! Great job, the only thing that I see as a slight issue is the measurements of the slide show but that's easy enough to fix so I can change that quick once I merge into master. 

Otherwise great job! Welcome to the open source contributor community!

**Comment by kenmazaika** [comment]
You rock, Eric! :) :+1:

**Comment by buddhaplex** [comment]
Thanks, Colin! Appreciate the tweak. And glad that was the only issue. :) good to be officially on board as an Open Source contributor!

E.

sent by science/magic

**Comment by buddhaplex** [comment]
Woohoo! Thanks, Ken. Back into some Flixter goodness and coding challenges this weekend!

sent by science/magic

**Pull request merged**
