### PR TITLE
Added contribute on github button to top nav

### PR DESCRIPTION
**Pull request by jonathanpike**
Added a button to the top nav directing students to [this blog post](http://community.thefirehoseproject.com/2015/08/19/How-To-Fork-A-Repo-And-Contribute.html) teaching them how to contribute on GitHub, as per issue #36.

### CODE REVIEW

**Comment by colinrubbert** [comment]
I like the idea of this but the button feels out of place and I think the color doesn't fit well with the rest of the site. It's possible that we could just place the "how to fork a repo and contribute" post to the top of the posts. I'll have to think on this some more, if you have some other suggestions I would love to hear it. Maybe even just changing the color might make it feel more like it belongs. Let me know what you think.

**Comment by jonathanpike** [comment]
I'll go back to the drawing board on how the link should be presented.  I do think that it should be in the nav, though.  Someone may not notice if the solution is to simply move the post to the top.  I'll make some changes and see what you think.

**Comment by colinrubbert** [comment]
I like the idea in the nav too but we want to make it look like it belongs there. Maybe instead of having the  background filled in we just color the border. Like how [slack](https://slack.com/) does it on their landing page for "Create a Team". It looks clean, stands out and feels like it belongs there.

**Comment by jonathanpike** [comment]
That's a really good idea.  In terms of border colour, do you think black, like the link text, would look good? And upon hover, should it fade to blue, like the rest of the text would?

**Comment by colinrubbert** [comment]
That's a good question. Maybe try and make it the light blue color we have or maybe even the green. Play around with it a little bit, take a couple screen shots and submit them here and we can choose what feels the best. I'm currently learning to that light blue, it just looks good to me with the Firehose icon.

**Comment by jonathanpike** [comment]
Sounds good!  I'll make that change tomorrow morning and post the screenshots.

**Comment by colinrubbert** [comment]
Awesome, thanks for doing the work. It's making the city much more professional.

**Comment by jonathanpike** [comment]
Okay, so I've made a few changes and tried out a few things.  However, I didn't like any except for what we talked about yesterday.  You were absolutely right that re: feeling like the button belongs.  Here's what it looks like. 

screen shot 2015-10-23 at 4 47 20 am
screen shot 2015-10-23 at 4 47 28 am

Let me know what you think.

**Comment by colinrubbert** [comment]
Starting to look good. What does it look like Blue w/o the grey background and a little thicker? Or even Blue with black text?

**Comment by jonathanpike** [comment]
Here it is a little thicker, without the grey background on hover: 

screen shot 2015-10-25 at 5 36 30 am
screen shot 2015-10-25 at 5 36 38 am

The thickness is 2px.  I tried 3px and it was too thick. 

Here it is with a blue border all the time: 

screen shot 2015-10-25 at 5 41 29 am
screen shot 2015-10-25 at 5 41 38 am

Personally, I like it best with a black border that transitions to blue on hover, like the first example I showed you.  Let me know what you think.

**Comment by colinrubbert** [comment]
Let's try the black border with blue hover, I think that will look pretty slick. Submit that one and I'll check it out.

**Comment by jonathanpike** [comment]
I just submitted the changes.  Also tweaked how it looks on mobile, if you want to check that out.

**Comment by colinrubbert** [comment]
I've got one more PR that I'm waiting on and then I will merge this PR, it looks good, I like it.

**Pull request merged**
