### PR TITLE
added a link in README to a post

### PR DESCRIPTION
**Pull request by chaudhary27**
Added a link in README.md section "Getting the blog up and running" to a post on medium explaining how the get the blog up and running on your system.

### CODE REVIEW

**Comment by colinrubbert** [comment]
Instead of just linking to medium, why don't you try your hand at creating a blog post in our environment. That way people don't have to come to our github page they can just read the post on the community site.

**Comment by chaudhary27** [comment]
I am nervous about writing an 'official' post. lol

**Comment by colinrubbert** [comment]
Lol... Don't worry about it yet, maybe play with it on your local install and get use to using markdown language. I'll merge this into master.

**Comment by kenmazaika** [comment]
Solid! :) :+1:

**Comment by kenmazaika** [comment]
Love the idea of having it be a native post on the blog too!

**Comment by colinrubbert** [comment]
I think what I'm going to do is make a video of the process that people can follow and then also add text of the process. @chaudhary27 did a lot of the ground work for me with his write up which is awesome!

**Pull request merged**
