### PR TITLE
Think I fixed the logo issue

### PR DESCRIPTION
**Pull request by robgraphix1**
I think I fixed the logo issue. That is, if I understood you correctly. Logo is sized to the same dimensions as the Firehose Project website and has equal margins on the top and bottom. Let me know...

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks great!  Thanks for the fix, @robgraphix1.  You rock! :+1:

**Comment by robgraphix1** [comment]
Glad to contribute!

**Comment by colinrubbert** [comment]
Awesome job! Thanks for the contribution!

**Comment by robgraphix1** [comment]
Glad to do it!

**Pull request merged**
