### PR TITLE
Added Call to Action

### PR DESCRIPTION
**Pull request by jonathanpike**
This is per issue #13. It can also address issue #17, but that would involve making the hero box taller (as more lines of text would break the mobile layout). 

There are two elements to this addition: 
## Index

On the index page, I've added an overlay over the hero image box that mimics the look of the main Firehose page.  I've included buttons that link to the main Firehose Page (to learn more) and to the sign up form for Firehose Intro (to sign up). This overlay does not appear on any other page. 

To do the typing, deleting, and re-typing, I've used [Typed.js](https://github.com/mattboldt/typed.js/), a jQuery plugin that made it super easy.  I've created a new folder called assets, and typed.js lives in the assets folder. 

I've tested it using Chrome's device mode for the mobile layout, so it should look alright.  Let me know if there are any problems. 
## Footer

On every other page, I've added a box to the footer that includes links to the same 2 pages.  I thought it would be a good idea to give visitors a way to find out more from any page.

### CODE REVIEW

**Comment by colinrubbert** [comment]
Looks pretty good. I'll merge it. I really like the call to action JS stuff on the landing page. Still have an issue with the navbar text but I'll change that quickly, it should be hidden on mobile devices.

**Comment by kenmazaika** [comment]
Love the typed.js stuff! :)  :+1:

**Comment by jonathanpike** [comment]
@colinrubbert Thanks.  What navbar text do you have an issue with?

**Comment by colinrubbert** [comment]
@jonathanpike I fixed it already. The `Firehose Community` text next to the icon, it was bleeding over. I just hid it on xs devices. Looks good now.

**Comment by jonathanpike** [comment]
@colinrubbert I thought that's what you meant, but I wasn't sure.  I noted that in issue #46, which I'll now close.

**Pull request merged**
